-- v3.3.9 챔피언 마스터 및 신규 경기 입력 제한
BEGIN;

CREATE TABLE IF NOT EXISTS champion (
    champion_code VARCHAR(50) PRIMARY KEY,
    name_en       VARCHAR(100) NOT NULL UNIQUE,
    name_ko       VARCHAR(100) NOT NULL UNIQUE,
    active_yn     BOOLEAN NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO champion(champion_code,name_en,name_ko,active_yn)
VALUES
('Aatrox','Aatrox','아트록스',true),
('Ahri','Ahri','아리',true),
('Akali','Akali','아칼리',true),
('Akshan','Akshan','아크샨',true),
('Alistar','Alistar','알리스타',true),
('Ambessa','Ambessa','암베사',true),
('Amumu','Amumu','아무무',true),
('Anivia','Anivia','애니비아',true),
('Annie','Annie','애니',true),
('Aphelios','Aphelios','아펠리오스',true),
('Ashe','Ashe','애쉬',true),
('AurelionSol','Aurelion Sol','아우렐리온 솔',true),
('Aurora','Aurora','오로라',true),
('Azir','Azir','아지르',true),
('Bard','Bard','바드',true),
('Belveth','Bel''Veth','벨베스',true),
('Blitzcrank','Blitzcrank','블리츠크랭크',true),
('Brand','Brand','브랜드',true),
('Braum','Braum','브라움',true),
('Briar','Briar','브라이어',true),
('Caitlyn','Caitlyn','케이틀린',true),
('Camille','Camille','카밀',true),
('Cassiopeia','Cassiopeia','카시오페아',true),
('Chogath','Cho''Gath','초가스',true),
('Corki','Corki','코르키',true),
('Darius','Darius','다리우스',true),
('Diana','Diana','다이애나',true),
('Draven','Draven','드레이븐',true),
('DrMundo','Dr. Mundo','문도 박사',true),
('Ekko','Ekko','에코',true),
('Elise','Elise','엘리스',true),
('Evelynn','Evelynn','이블린',true),
('Ezreal','Ezreal','이즈리얼',true),
('Fiddlesticks','Fiddlesticks','피들스틱',true),
('Fiora','Fiora','피오라',true),
('Fizz','Fizz','피즈',true),
('Galio','Galio','갈리오',true),
('Gangplank','Gangplank','갱플랭크',true),
('Garen','Garen','가렌',true),
('Gnar','Gnar','나르',true),
('Gragas','Gragas','그라가스',true),
('Graves','Graves','그레이브즈',true),
('Gwen','Gwen','그웬',true),
('Hecarim','Hecarim','헤카림',true),
('Heimerdinger','Heimerdinger','하이머딩거',true),
('Hwei','Hwei','흐웨이',true),
('Illaoi','Illaoi','일라오이',true),
('Irelia','Irelia','이렐리아',true),
('Ivern','Ivern','아이번',true),
('Janna','Janna','잔나',true),
('JarvanIV','Jarvan IV','자르반 4세',true),
('Jax','Jax','잭스',true),
('Jayce','Jayce','제이스',true),
('Jhin','Jhin','진',true),
('Jinx','Jinx','징크스',true),
('KSante','K''Sante','크산테',true),
('Kaisa','Kai''Sa','카이사',true),
('Kalista','Kalista','칼리스타',true),
('Karma','Karma','카르마',true),
('Karthus','Karthus','카서스',true),
('Kassadin','Kassadin','카사딘',true),
('Katarina','Katarina','카타리나',true),
('Kayle','Kayle','케일',true),
('Kayn','Kayn','케인',true),
('Kennen','Kennen','케넨',true),
('Khazix','Kha''Zix','카직스',true),
('Kindred','Kindred','킨드레드',true),
('Kled','Kled','클레드',true),
('KogMaw','Kog''Maw','코그모',true),
('Leblanc','LeBlanc','르블랑',true),
('LeeSin','Lee Sin','리 신',true),
('Leona','Leona','레오나',true),
('Lillia','Lillia','릴리아',true),
('Lissandra','Lissandra','리산드라',true),
('Locke','Locke','로크',true),
('Lucian','Lucian','루시안',true),
('Lulu','Lulu','룰루',true),
('Lux','Lux','럭스',true),
('Malphite','Malphite','말파이트',true),
('Malzahar','Malzahar','말자하',true),
('Maokai','Maokai','마오카이',true),
('MasterYi','Master Yi','마스터 이',true),
('Mel','Mel','멜',true),
('Milio','Milio','밀리오',true),
('MissFortune','Miss Fortune','미스 포츈',true),
('Mordekaiser','Mordekaiser','모데카이저',true),
('Morgana','Morgana','모르가나',true),
('Naafiri','Naafiri','나피리',true),
('Nami','Nami','나미',true),
('Nasus','Nasus','나서스',true),
('Nautilus','Nautilus','노틸러스',true),
('Neeko','Neeko','니코',true),
('Nidalee','Nidalee','니달리',true),
('Nilah','Nilah','닐라',true),
('Nocturne','Nocturne','녹턴',true),
('Nunu','Nunu & Willump','누누와 윌럼프',true),
('Olaf','Olaf','올라프',true),
('Orianna','Orianna','오리아나',true),
('Ornn','Ornn','오른',true),
('Pantheon','Pantheon','판테온',true),
('Poppy','Poppy','뽀삐',true),
('Pyke','Pyke','파이크',true),
('Qiyana','Qiyana','키아나',true),
('Quinn','Quinn','퀸',true),
('Rakan','Rakan','라칸',true),
('Rammus','Rammus','람머스',true),
('RekSai','Rek''Sai','렉사이',true),
('Rell','Rell','렐',true),
('Renata','Renata Glasc','레나타 글라스크',true),
('Renekton','Renekton','레넥톤',true),
('Rengar','Rengar','렝가',true),
('Riven','Riven','리븐',true),
('Rumble','Rumble','럼블',true),
('Ryze','Ryze','라이즈',true),
('Samira','Samira','사미라',true),
('Sejuani','Sejuani','세주아니',true),
('Senna','Senna','세나',true),
('Seraphine','Seraphine','세라핀',true),
('Sett','Sett','세트',true),
('Shaco','Shaco','샤코',true),
('Shen','Shen','쉔',true),
('Shyvana','Shyvana','쉬바나',true),
('Singed','Singed','신지드',true),
('Sion','Sion','사이온',true),
('Sivir','Sivir','시비르',true),
('Skarner','Skarner','스카너',true),
('Smolder','Smolder','스몰더',true),
('Sona','Sona','소나',true),
('Soraka','Soraka','소라카',true),
('Swain','Swain','스웨인',true),
('Sylas','Sylas','사일러스',true),
('Syndra','Syndra','신드라',true),
('TahmKench','Tahm Kench','탐 켄치',true),
('Taliyah','Taliyah','탈리야',true),
('Talon','Talon','탈론',true),
('Taric','Taric','타릭',true),
('Teemo','Teemo','티모',true),
('Thresh','Thresh','쓰레쉬',true),
('Tristana','Tristana','트리스타나',true),
('Trundle','Trundle','트런들',true),
('Tryndamere','Tryndamere','트린다미어',true),
('TwistedFate','Twisted Fate','트위스티드 페이트',true),
('Twitch','Twitch','트위치',true),
('Udyr','Udyr','우디르',true),
('Urgot','Urgot','우르곳',true),
('Varus','Varus','바루스',true),
('Vayne','Vayne','베인',true),
('Veigar','Veigar','베이가',true),
('Velkoz','Vel''Koz','벨코즈',true),
('Vex','Vex','벡스',true),
('Vi','Vi','바이',true),
('Viego','Viego','비에고',true),
('Viktor','Viktor','빅토르',true),
('Vladimir','Vladimir','블라디미르',true),
('Volibear','Volibear','볼리베어',true),
('Warwick','Warwick','워윅',true),
('MonkeyKing','Wukong','오공',true),
('Xayah','Xayah','자야',true),
('Xerath','Xerath','제라스',true),
('XinZhao','Xin Zhao','신 짜오',true),
('Yasuo','Yasuo','야스오',true),
('Yone','Yone','요네',true),
('Yorick','Yorick','요릭',true),
('Yunara','Yunara','유나라',true),
('Yuumi','Yuumi','유미',true),
('Zaahen','Zaahen','자헨',true),
('Zac','Zac','자크',true),
('Zed','Zed','제드',true),
('Zeri','Zeri','제리',true),
('Ziggs','Ziggs','직스',true),
('Zilean','Zilean','질리언',true),
('Zoe','Zoe','조이',true),
('Zyra','Zyra','자이라',true)
ON CONFLICT (champion_code)
DO UPDATE SET
    name_en=EXCLUDED.name_en,
    name_ko=EXCLUDED.name_ko,
    active_yn=EXCLUDED.active_yn,
    updated_at=CURRENT_TIMESTAMP;

ALTER TABLE inhouse_match_player
    ADD COLUMN IF NOT EXISTS champion_code VARCHAR(50);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
         WHERE conname='fk_match_player_champion'
    ) THEN
        ALTER TABLE inhouse_match_player
            ADD CONSTRAINT fk_match_player_champion
            FOREIGN KEY(champion_code)
            REFERENCES champion(champion_code)
            NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
         WHERE conname='ck_match_player_champion_required'
    ) THEN
        ALTER TABLE inhouse_match_player
            ADD CONSTRAINT ck_match_player_champion_required
            CHECK (champion_code IS NOT NULL)
            NOT VALID;
    END IF;
END $$;

COMMIT;
